name: style

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  format:
    name: "Format with black"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: psf/black@stable