name: test

on:
  push:
      branches:
        - "main"
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: pytest on python ${{ matrix.python }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Activate venv
        run: |
          source .venv/bin/activate
          echo "VIRTUAL_ENV=${VIRTUAL_ENV}" >> $GITHUB_ENV
          echo "${VIRTUAL_ENV}/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=${VIRTUAL_ENV}"
      - name: Run pytest
        run: |
          pytest \
            --cov-report="xml:reports/coverage.xml" \
            --cov=src/ \
            --junitxml="reports/junit.xml" \
            tests/
      - name: Publish to Codecov
        if: success() || failure()
        uses: codecov/codecov-action@v4.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./reports/coverage.xml
